---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectivity-consumer
  namespace: connectivity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connectivity-consumer
  template:
    metadata:
      labels:
        app: connectivity-consumer
    spec:
      containers:
      - name: consumer
        image: alejandrodgz/connectivity-microservice:latest
        imagePullPolicy: Always
        command: ["python", "manage.py", "consume_document_auth"]
        envFrom:
        - configMapRef:
            name: connectivity-config
        - secretRef:
            name: connectivity-secrets
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 30
          periodSeconds: 30
