apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: connectivity-dev

bases:
  - ../../base

nameSuffix: -dev

commonLabels:
  environment: development

replicas:
  - name: connectivity-service
    count: 1
  - name: connectivity-document-consumer
    count: 1

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: connectivity-service
      spec:
        template:
          spec:
            containers:
              - name: connectivity-service
                resources:
                  requests:
                    cpu: "100m"
                    memory: "128Mi"
                  limits:
                    cpu: "500m"
                    memory: "256Mi"

configMapGenerator:
  - name: connectivity-config
    behavior: merge
    literals:
      - DEBUG=True
      - LOG_LEVEL=DEBUG
      - ALLOWED_HOSTS=*

images:
  - name: REPOSITORY/connectivity-microservice
    newTag: develop-latest
