apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: connectivity

bases:
  - ../../base

commonLabels:
  environment: production

replicas:
  - name: connectivity-service
    count: 3
  - name: connectivity-document-consumer
    count: 2

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: connectivity-service
      spec:
        template:
          spec:
            containers:
              - name: connectivity-service
                resources:
                  requests:
                    cpu: "200m"
                    memory: "256Mi"
                  limits:
                    cpu: "1000m"
                    memory: "512Mi"

configMapGenerator:
  - name: connectivity-config
    behavior: merge
    literals:
      - DEBUG=False
      - LOG_LEVEL=WARNING
      - ALLOWED_HOSTS=connectivity.example.com,api.connectivity.example.com

images:
  - name: REPOSITORY/connectivity-microservice
    newTag: main-latest
